# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

admm_gauss_testing <- function(M, korder, y, x, w, theta, z, u, rho, lam_z, linear_solver, tol) {
    .Call(`_rtestim_admm_gauss_testing`, M, korder, y, x, w, theta, z, u, rho, lam_z, linear_solver, tol)
}

prox_newton_testing <- function(M, Minner, Mline, korder, y, x, w, lambda, ls_alpha, ls_gamma, linear_solver, tol) {
    .Call(`_rtestim_prox_newton_testing`, M, Minner, Mline, korder, y, x, w, lambda, ls_alpha, ls_gamma, linear_solver, tol)
}

smat_to_mat <- function(sparseMat, k, equal_spaced) {
    .Call(`_rtestim_smat_to_mat`, sparseMat, k, equal_spaced)
}

configure_denseD_test <- function(x, k) {
    .Call(`_rtestim_configure_denseD_test`, x, k)
}

linear_single_solve_test <- function(linear_solver, y, weights, x, rho, adj_mean) {
    .Call(`_rtestim_linear_single_solve_test`, linear_solver, y, weights, x, rho, adj_mean)
}

rtestim_path <- function(y, x, w, korder, lambda, lambdamax = -1, lambdamin = -1, nsol = 100L, rho = -1, maxiter = 1e5L, maxiter_newton = 50L, maxiter_line = 5L, tolerance = 1e-3, lambda_min_ratio = 1e-4, ls_alpha = 0.5, ls_gamma = 0.9, linear_solver = 2L, verbose = 0L) {
    .Call(`_rtestim_rtestim_path`, y, x, w, korder, lambda, lambdamax, lambdamin, nsol, rho, maxiter, maxiter_newton, maxiter_line, tolerance, lambda_min_ratio, ls_alpha, ls_gamma, linear_solver, verbose)
}

rcpp_tvdz <- function(y, z, lambda) {
    .Call(`_rtestim_rcpp_tvdz`, y, z, lambda)
}

rcpp_tvd <- function(y, lambda) {
    .Call(`_rtestim_rcpp_tvd`, y, lambda)
}

rcpp_wtvd <- function(y, lambda, weights) {
    .Call(`_rtestim_rcpp_wtvd`, y, lambda, weights)
}

get_Dtil <- function(k, xd) {
    .Call(`_rtestim_get_Dtil`, k, xd)
}

get_D <- function(k, xd) {
    .Call(`_rtestim_get_D`, k, xd)
}

create_lambda_test <- function(lambda, lambdamin, lambdamax, lambda_min_ratio, nsol) {
    .Call(`_rtestim_create_lambda_test`, lambda, lambdamin, lambdamax, lambda_min_ratio, nsol)
}

doDv <- function(v, k, xd) {
    .Call(`_rtestim_doDv`, v, k, xd)
}

doDtv <- function(v, k, xd) {
    .Call(`_rtestim_doDtv`, v, k, xd)
}

one_norm <- function(z) {
    .Call(`_rtestim_one_norm`, z)
}

pois_obj <- function(ord, y, x, w, theta, lambda) {
    .Call(`_rtestim_pois_obj`, ord, y, x, w, theta, lambda)
}

centered_data <- function(y, w, theta) {
    .Call(`_rtestim_centered_data`, y, w, theta)
}

line_search <- function(s, lambda, alpha, gamma, y, x, w, n, ord, theta, theta_old, M) {
    .Call(`_rtestim_line_search`, s, lambda, alpha, gamma, y, x, w, n, ord, theta, theta_old, M)
}

compute_gcd <- function(x) {
    .Call(`_rtestim_compute_gcd`, x)
}

calc_delays <- function(x, y) {
    .Call(`_rtestim_calc_delays`, x, y)
}

get_dk_mat <- function(k, xd, tf_weighting) {
    .Call(`_rtestim_get_dk_mat`, k, xd, tf_weighting)
}

get_penalty_mat <- function(k, xd) {
    .Call(`_rtestim_get_penalty_mat`, k, xd)
}

get_lambda_max <- function(x, y, weights, k) {
    .Call(`_rtestim_get_lambda_max`, x, y, weights, k)
}

calc_degrees_of_freedom <- function(v, k, tol) {
    .Call(`_rtestim_calc_degrees_of_freedom`, v, k, tol)
}

get_lambda_seq_r <- function(lambda, lambda_max, lambda_min, lambda_min_ratio, n_lambda) {
    .Call(`_rtestim_get_lambda_seq_r`, lambda, lambda_max, lambda_min, lambda_min_ratio, n_lambda)
}

Dkv <- function(v, k, xd, tf_weighting) {
    .Call(`_rtestim_Dkv`, v, k, xd, tf_weighting)
}

rcpp_wtvdz <- function(y, z, lambda, weights) {
    .Call(`_rtestim_rcpp_wtvdz`, y, z, lambda, weights)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call(`_rtestim_RcppExport_registerCCallable`)
})
